name: Build Crazy Elevator Web

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build LÖVE package
        run: |
          cd games/crazy-elevator
          zip -r CrazyElevator.love main.lua

      - name: Upload LÖVE package
        uses: actions/upload-artifact@v4
        with:
          name: Crazy-Elevator-Love
          path: games/crazy-elevator/CrazyElevator.love
